export const WS_CONNECTION_START = "WS_CONNECTION_START"
export const WS_CONNECTION_SUCCESS = "WS_CONNECTION_SUCCESS"
export const WS_GET_MESSAGE = "WS_GET_MESSAGE"
export const WS_SEND_MESSAGE = "WS_SEND_MESSAGE"
export const WS_CONNECTION_CLOSED = "WS_CONNECTION_CLOSED"
export const WS_CONNECTION_ERROR = "WS_CONNECTION_ERROR"

export const wsAction = {
   wsInit: WS_CONNECTION_START,
   onOpen: WS_CONNECTION_SUCCESS,
   onMessage: WS_GET_MESSAGE,
   wsSendMessage: WS_SEND_MESSAGE,
   onClose: WS_CONNECTION_CLOSED,
   onError: WS_CONNECTION_ERROR
}